//
//  MainShowPresenter.swift
//  LovePlanetDemo
//
//  Created by msm72 on 21.09.17.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Presentation Logic protocols
protocol MainShowPresentationLogic {
    func presentSomething(response: MainShowModels.Something.ResponseModel)
}

class MainShowPresenter: MainShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: MainShowDisplayLogic?
    
    
    // MARK: - Presentation Logic implementation
    func presentSomething(response: MainShowModels.Something.ResponseModel) {
        let viewModel = MainShowModels.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
