//
//  MainShowRouter.swift
//  LovePlanetDemo
//
//  Created by msm72 on 21.09.17.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
@objc protocol MainShowRoutingLogic {
    func routeToUsersShowScene()
}

protocol MainShowDataPassing {
    var dataStore: MainShowDataStore? { get }
}

class MainShowRouter: NSObject, MainShowRoutingLogic, MainShowDataPassing {
    // MARK: - Properties
    weak var viewController: MainShowViewController?
    var dataStore: MainShowDataStore?
    
    
    // MARK: - Routing
    func routeToUsersShowScene() {
        let destinationNC = UINavigationController.init(rootViewController: UsersListShowViewController.init(nibName: nil, bundle: nil))
        navigateToUsersListShowScene(source: viewController!, destination: destinationNC)
    }
    
    
    // MARK: - Navigation
    func navigateToUsersListShowScene(source: MainShowViewController, destination: UINavigationController) {
        destination.modalTransitionStyle = .flipHorizontal
        source.show(destination, sender: nil)
    }
    
    
    // MARK: - Passing data
    //func passDataToSomewhere(source: MainShowDataStore, destination: inout SomewhereDataStore) {
    //  destination.name = source.name
    //}
}
