//
//  UsersListShowRouter.swift
//  LovePlanetDemo
//
//  Created by msm72 on 21.09.17.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
@objc protocol UsersListShowRoutingLogic {
    func routeToUserShowScene()
}

protocol UsersListShowDataPassing {
    var dataStore: UsersListShowDataStore? { get }
}

class UsersListShowRouter: NSObject, UsersListShowRoutingLogic, UsersListShowDataPassing {
    // MARK: - Properties
    weak var viewController: UsersListShowViewController?
    var dataStore: UsersListShowDataStore?
    
    
    // MARK: - Routing
    func routeToUserShowScene() {
        let destinationVC = UserShowViewController()
        var destinationDS = destinationVC.router!.dataStore!
        passDataToUserShowScene(source: dataStore!, destination: &destinationDS)
        navigateToUserShowScene(source: viewController!, destination: destinationVC)
    }
    
    
    // MARK: - Navigation
    func navigateToUserShowScene(source: UsersListShowViewController, destination: UserShowViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    
    // MARK: - Passing data
    func passDataToUserShowScene(source: UsersListShowDataStore, destination: inout UserShowDataStore) {
        let selectedRow = viewController?.tableView.indexPathForSelectedRow?.row
        
        guard selectedRow != nil else {
            return
        }
        
        destination.user = source.dataSource[selectedRow!]
    }
}
