//
//  UsersListShowPresenter.swift
//  LovePlanetDemo
//
//  Created by msm72 on 21.09.17.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Presentation Logic protocols
protocol UsersListShowPresentationLogic {
    func usersListPreparePresent(fromResponseModel responseModel: UsersListShowModels.Users.ResponseModel)
    func userDeletePreparePresent(fromResponseModel responseModel: UsersListShowModels.Users.ResponseModel)
}

class UsersListShowPresenter: UsersListShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: UsersListShowDisplayLogic?
    
    
    // MARK: - Presentation Logic implementation
    func usersListPreparePresent(fromResponseModel responseModel: UsersListShowModels.Users.ResponseModel) {
        let viewModel = UsersListShowModels.Users.ViewModel(dataSource: responseModel.dataSource)
        viewController?.usersListPresent(fromViewModel: viewModel)
    }

    func userDeletePreparePresent(fromResponseModel responseModel: UsersListShowModels.Users.ResponseModel) {
        let viewModel = UsersListShowModels.Users.ViewModel(dataSource: nil)
        viewController?.userDeletePresent(fromViewModel: viewModel)
    }
}
