//
//  UsersListShowRouter.swift
//  LovePlanetDemo
//
//  Created by msm72 on 21.09.17.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
@objc protocol UsersListShowRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol UsersListShowDataPassing {
    var dataStore: UsersListShowDataStore? { get }
}

class UsersListShowRouter: NSObject, UsersListShowRoutingLogic, UsersListShowDataPassing {
    // MARK: - Properties
    weak var viewController: UsersListShowViewController?
    var dataStore: UsersListShowDataStore?
    
    
    // MARK: - Routing
    //func routeToSomewhere(segue: UIStoryboardSegue?) {
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    
    // MARK: - Navigation
    //func navigateToSomewhere(source: UsersListShowViewController, destination: SomewhereViewController) {
    //  source.show(destination, sender: nil)
    //}
    
    
    // MARK: - Passing data
    //func passDataToSomewhere(source: UsersListShowDataStore, destination: inout SomewhereDataStore) {
    //  destination.name = source.name
    //}
}
