//
//  UserShowModels.swift
//  LovePlanetDemo
//
//  Created by msm72 on 21.09.17.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Data models
enum UserShowModels {
    // MARK: - User info
    struct UserFormFields {
        var codeID: Int16?
        var firstName: String
        var lastName: String
        var isFemale: Bool
        var birthday: Date
    }
    

    // MARK: - Use cases
    enum User {
        struct RequestModel {
            let formFields: UserFormFields
        }
        
        struct ResponseModel {
        }
        
        struct ViewModel {
        }
    }
}
